inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - '.git/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Airbnb/ClassOrModuleDeclaredInWrongFile:
  Exclude:
    - 'app/graphql/**/*'

Airbnb/ModuleMethodInWrongFile:
  Exclude:
    - 'app/graphql/**/*'

Airbnb/ContinuationSlash:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 100
  AllowURI: true
  IgnoredPatterns:
    - '\A\s*#'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
